package org.hubian.hreport.service.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.hubian.hreport.service.model.generated.ReportFieldSchema;
import org.hubian.hreport.service.model.generated.ReportFieldSchemaExample;

public interface ReportFieldSchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int countByExample(ReportFieldSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int deleteByExample(ReportFieldSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int insert(ReportFieldSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int insertSelective(ReportFieldSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    List<ReportFieldSchema> selectByExampleWithRowbounds(ReportFieldSchemaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    List<ReportFieldSchema> selectByExample(ReportFieldSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    ReportFieldSchema selectByPrimaryKey(Integer fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportFieldSchema record, @Param("example") ReportFieldSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportFieldSchema record, @Param("example") ReportFieldSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportFieldSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_field_schema
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportFieldSchema record);
}