package org.hubian.hreport.service.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.hubian.hreport.service.model.generated.ReportTableSchema;
import org.hubian.hreport.service.model.generated.ReportTableSchemaExample;

public interface ReportTableSchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int countByExample(ReportTableSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int deleteByExample(ReportTableSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int insert(ReportTableSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int insertSelective(ReportTableSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    List<ReportTableSchema> selectByExampleWithRowbounds(ReportTableSchemaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    List<ReportTableSchema> selectByExample(ReportTableSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    ReportTableSchema selectByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportTableSchema record, @Param("example") ReportTableSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportTableSchema record, @Param("example") ReportTableSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportTableSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_table_schema
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportTableSchema record);
}