package org.hubian.hreport.service.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.hubian.hreport.service.model.generated.ReportData;
import org.hubian.hreport.service.model.generated.ReportDataExample;

public interface ReportDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int countByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int deleteByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int insert(ReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int insertSelective(ReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    List<ReportData> selectByExampleWithRowbounds(ReportDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    List<ReportData> selectByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    ReportData selectByPrimaryKey(Long dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportData record, @Param("example") ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportData record, @Param("example") ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportData record);
}